Allow to modify committed words
fcitx/fcitx5-unikey pull request #34
Opened 2022-11-30 09:06 UTC by trmdi

Requires the client to have SurroundingText capability.
Currently only support precomposed Unicode, which is the most popular and recommended charset in Vietnam nowadays.

2022-11-30 14:43 UTC, wengxt commented
to get notification when surrounding text updated, check Instance::watchEvent and InputContextSurroundingTextUpdated

2022-12-02 11:38 UTC, trmdi commented
> to get notification when surrounding text updated, check Instance::watchEvent and InputContextSurroundingTextUpdated

This works well in detecting mouse clicked and key pressed. But whenever I commit the preedit, I also get 2 extra events. Is there any way to ignore these 2 unwanted ones?

2022-12-02 11:40 UTC, wengxt commented
> > to get notification when surrounding text updated, check Instance::watchEvent and InputContextSurroundingTextUpdated
> 
> This works well in detecting mouse clicked and key pressed. But whenever I commit the preedit, I also get 2 extra events. Is there any way to ignore these 2 unwanted ones?

afaik, no. you might want to check if the surrounding change matches the recent commit or sth.

2022-12-05 16:03 UTC, wengxt commented
it's not me add such feature, it comes from original unikey port.

2022-12-05 16:27 UTC, trmdi commented
@zenfas may want to help test?

2022-12-05 17:05 UTC, zenfas commented
I will test this PR tomorrow.
@tulequ: does Wengxt correct about explanation of "Restore typing state..."

P/S: Underline of preedit: most of VN don't like it, that why ibus-bamboo try some methods (and trick) to help people hide it.  Then people is welcome it to replace ibus-unikey.

2022-12-06 01:01 UTC, wengxt commented
not using the underline is very easy, just one line change. 

but it’s very dangerous that tricks you the text is already accepted by the application. It could easily causes confusion that people think it’s committed text while it’s not.

2022-12-06 01:09 UTC, trmdi commented
Yes, that's why I, as a VN person, still prefer to display the preedit. Not really a problem to me.

2022-12-06 03:00 UTC, zenfas commented
> not using the underline is very easy, just one line change.
> 
> but it’s very dangerous that tricks you the text is already accepted by the application. It could easily causes confusion that people think it’s committed text while it’s not.
I think it belong to technical, normal user don't care. Microsoft already switched to non-underline for Vietnamese recently.

2022-12-06 03:04 UTC, zenfas commented
@trmdi I see some error on Kubuntu 22.10
![Libreoffic](https://user-images.githubusercontent.com/66258788/205800852-ea4ce400-0fd8-4165-8325-330f28a35c85.gif)
![Kate](https://user-images.githubusercontent.com/66258788/205800914-67c7a8f9-c363-47c8-a1a4-27002d3bfd11.gif)

2022-12-06 03:09 UTC, trmdi commented
> I see some error on Kubuntu 22.10

Modifying from the middle of a word is not allowed, that's my intention.

2022-12-06 03:14 UTC, zenfas commented
If use mouse, more error than ← key. LibreOffice, Firefox (snap) not work also
Surouding, I think it can and should check before and after click point

2022-12-06 03:35 UTC, zenfas commented
@trmdi  Warning when I compile:

[ 88%] Building CXX object src/CMakeFiles/unikey.dir/unikey-im.cpp.o
/home/kubuntu/Downloads/fcitx5-unikey-feature-modify-committed-word/src/unikey-im.cpp: In member function ‘void fcitx::UnikeyState::rebuildPreedit()’:
/home/kubuntu/Downloads/fcitx5-unikey-feature-modify-committed-word/src/unikey-im.cpp:283:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
  283 |         for (int i = 1; i <= length; ++i) {
      |                         ~~^~~~~~~~~
[ 90%] Linking CXX shared module libunikey.so

2022-12-06 09:47 UTC, trmdi commented
@zenfas Maybe better now.

2022-12-07 02:05 UTC, zenfas commented
1) Not work on LibreOffice, Firefox. On Firefox, some text box disappear when I type (mail subject on my webmail)
2) If edit more than 2 words, second word not impact, always point to first word. Sometime make error when I move cursor go to other, character converter like not commit when cursor focus out
![Firefox](https://user-images.githubusercontent.com/66258788/206069647-2ba161de-8536-4a4b-9199-41c06d94bff9.gif)
![Kate1](https://user-images.githubusercontent.com/66258788/206069721-ba572373-f1aa-4964-adb7-77f8ffd96595.gif)

2022-12-07 02:12 UTC, trmdi commented
Changing the cursor position with the mouse before committing the preedit causes some weird issues, it already happens before this patch: https://github.com/fcitx/fcitx5-unikey/issues/35
Please show the underline while recording the screen.

I also noticed in FF, sometimes the input context loses the Surrounding capability. Not sure about this bug. @wengxt

2022-12-07 02:20 UTC, zenfas commented
Ok, I will turn on underline next time.
For more info, previous patch yesterday made my keyboard error when I type "w", "f", word disappear and impact all keyboards (English or VN), ibus or fcitx5. I don't know why only addon fcitx5-unikey effect all system

2022-12-09 11:09 UTC, zenfas commented
I tested with ibus-keyman (Vietnamese_telex) on Kubuntu 23.04 (daily build) KDE Wayland session, it work well on Kate, I can edit any word with mouse, even I insert in middle of word
Fyi @trmdi  @wengxt

2022-12-14 14:33 UTC, trmdi commented
@zenfas 
Modifying from the middle has been enabled.
Have you found any other issue besdes the ones caused by clicking the mouse while typing?

2022-12-14 14:55 UTC, zenfas commented
Not yet find out other issue. I will test new one tmr
Can you take a look on [ibus-keyman](https://github.com/keymanapp/keyman/tree/master/linux/ibus-keyman), I see they solve good for mouse moving when edit on Kate even Wayland. It maybe help for issue #35 also @trmdi

2022-12-14 17:27 UTC, wengxt commented
@trmdi one suggestion, can we rebuild preedit only when backspace is pressed?

due to the unreliable fact of surrounding (buggy), I'd like to keep the old behavior as is whenever possible.

2022-12-14 17:27 UTC, wengxt requested changes

2022-12-14 17:49 UTC, trmdi commented
> @trmdi one suggestion, can we rebuild preedit only when backspace is pressed?
> 
> due to the unreliable fact of surrounding (buggy), I'd like to keep the old behavior as is whenever possible.

For example, when the user modifies "tieng" to "tiếng", he just need to type "es" after "tieng". That's the way VN users are familiar with.
If we rebuild preedit only when backspace is pressed, we will remove the last letter "g" and have to retype it. That's not a good way to start rebuilding preedit, I think.

2022-12-14 18:08 UTC, wengxt commented
ok, got it. I think it makes sense

> > @trmdi one suggestion, can we rebuild preedit only when backspace is pressed?
> > due to the unreliable fact of surrounding (buggy), I'd like to keep the old behavior as is whenever possible.
> 
> For example, when the user modifies "tieng" to "tiếng", he just need to type "es" after "tieng". That's the way VN users are familiar with. If we rebuild preedit only when backspace is pressed, we will remove the last letter "g" and have to retype it. That's not a good way to start rebuilding preedit, I think.

Ok got it, that make sense. Then another suggestion, can we delay the surrounding rebuild until the point we really have too?

For example,

2022-12-15 01:57 UTC, trmdi commented on src/unikey-im.cpp
> +            result.insert(UnicodeTable[i]);
This function is used only in the rebuildSurrounding() function to check if an char is a auto committed word. That works fine for non-VN letters like a, b, c...

Now I make use of it for the new feature, it becomes wrong when you check VN letters like "â", "ê"... The reason is Unikey uses the UnicodeTable, not the UnicodeComposite one.

2022-12-15 02:59 UTC, zenfas commented
1) Mouse moving still make error (important for normal user use mouse a lot, not like dev)
![Peek 2022-12-15 08-47](https://user-images.githubusercontent.com/66258788/207761897-2d39997c-9a29-45cb-9836-1b8a77724bde.gif)
I think shouldn't pust to mainline if can solve mouse moving problem.
2) I test on ibus-keyman below:
![Peek 2022-12-15 08-58keyman](https://user-images.githubusercontent.com/66258788/207762064-40e492b4-20ad-4bd2-8287-5d93a448f830.gif)

fyi @trmdi

2022-12-15 03:09 UTC, trmdi commented
Yes, it should be solved but I still have no idea how ibus-keyman does that. Maybe it always commits preedit after each key event?

2022-12-15 03:19 UTC, wengxt commented
> Yes, it should be solved but I still have no idea how ibus-keyman does that. Maybe it always commits preedit after each key event?

Yes, actually fcitx5-keyman is doing the same. It doesn't use preedit at all. i'm not asking you to do the same though, preedit is much, much more reliable than surrounding text.

I noticed that ibus gtk im module is connecting to client widget mouse click event. I could do some hack in fcitx5-gtk to capture mouse click at application level and send a reset to fcitx.

As for kate case, fix on qt and kate side is more ideal (and shouldn't be hard).

2022-12-15 03:29 UTC, zenfas commented
@trmdi  new error for new commit make double word not yes commit on gtk app when mouse focus out current app
![Peek 2022-12-15 10-23gedit](https://user-images.githubusercontent.com/66258788/207765714-9273728e-cea9-44d4-af22-d3f3013d4d75.gif)

2022-12-15 03:36 UTC, zenfas commented
@wengxt I tested ibus-keyman work well for edit word on kate and gedit, fcitx5-keyman not work. Maybe something different between ibus and fcitx.

2022-12-15 03:36 UTC, wengxt commented
> @trmdi new error for new commit make double word not yes commit on gtk app when mouse focus out current app ![Peek 2022-12-15 10-23gedit](https://user-images.githubusercontent.com/66258788/207765714-9273728e-cea9-44d4-af22-d3f3013d4d75.gif) [ ![Peek 2022-12-15 10-23gedit](https://user-images.githubusercontent.com/66258788/207765714-9273728e-cea9-44d4-af22-d3f3013d4d75.gif) ](https://user-images.githubusercontent.com/66258788/207765714-9273728e-cea9-44d4-af22-d3f3013d4d75.gif) [ ](https://user-images.githubusercontent.com/66258788/207765714-9273728e-cea9-44d4-af22-d3f3013d4d75.gif)

This is what I'm trying to say in https://github.com/fcitx/fcitx5-unikey/pull/34#discussion_r1041605812

2022-12-15 03:40 UTC, trmdi commented on src/unikey-im.cpp
> +    state->commit();
Reverted.

2022-12-15 03:40 UTC, trmdi commented on src/unikey-config.h
> +    Option<bool> modifySurroundingText{this, "ModifySurroundingText",
Add "(experimental)" to the description.

2022-12-15 03:45 UTC, trmdi commented
> I noticed that ibus gtk im module is connecting to client widget mouse click event. I could do some hack in fcitx5-gtk to capture mouse click at application level and send a reset to fcitx.
> 
> As for kate case, fix on qt and kate side is more ideal (and shouldn't be hard).

Could this also be applied to fcitx-qt? I think committing the preedit when pressing the mouse is fine in any case>

2022-12-15 03:49 UTC, trmdi commented
@zenfas Can ibus-keyman modify VN words like "cơ" -> "cô" ? Just curious.

2022-12-15 04:01 UTC, zenfas commented
> @zenfas Can ibus-keyman modify VN words like "cơ" -> "cô" ? Just curious.

[Vietnamese_telex](https://raw.githubusercontent.com/keymanapp/keyboards/master/release/v/vietnamese_telex/source/vietnamese_telex.kmn) keyboard have some limitations, only change accent, can't change vowel
keymanapp/keyboards/#2080

2022-12-15 13:33 UTC, wengxt commented
@trmdi such hack could interfere with qt invokeAction implementation, so probably shouldn't be used in qt. as I said, try to fix within qt instead of hack.

2022-12-15 13:42 UTC, trmdi commented
There is still an issue with Kate. When you have only one letter "a" in the document (a committed str), then press Ctrl+A, and type another "a", the existing "a" is not removed before the new "a" is inserted. It does not happend in other places, also not happen in Kate when you select the text with Shift+arrow key. Not sure how to solve this issue. 
Do you have any suggestion @wengxt ?

2022-12-18 03:03 UTC, trmdi commented
With the latest commits in fcitx5-gtk, switching from rebuiltPreedit in Pastebin's textbox on Firefox to another app (using the mouse) doubles the rebuiltPreedit str. Not sure why. This doesn't happen in Github's textbox.

2022-12-19 14:00 UTC, trmdi commented
@zenfas Do you have experience in setting up fcitx-unikey in Debian? https://bugs.documentfoundation.org/show_bug.cgi?id=152519

2022-12-19 14:13 UTC, zenfas commented
> @zenfas Do you have experience in setting up fcitx-unikey in Debian? https://bugs.documentfoundation.org/show_bug.cgi?id=152519
He misunderstood your report, maybe he think fcitx5-unikey is standalone app, and he maybe never use fcitx before.
Setting up on debian similar in other distro, but can use im-config to choose ibus or fcitx more easily

2022-12-19 14:22 UTC, trmdi commented
> > @zenfas Do you have experience in setting up fcitx-unikey in Debian? https://bugs.documentfoundation.org/show_bug.cgi?id=152519
> > He misunderstood your report, maybe he think fcitx5-unikey is standalone app, and he maybe never use fcitx before.
> > Setting up on debian similar in other distro, open fcitx5 and add Unikey, but can use im-config to choose ibus or fcitx more easily

Can you write something there? I've never used Debian.
TIA.

2022-12-19 14:36 UTC, zenfas commented
> > > @zenfas Do you have experience in setting up fcitx-unikey in Debian? https://bugs.documentfoundation.org/show_bug.cgi?id=152519
> > > He misunderstood your report, maybe he think fcitx5-unikey is standalone app, and he maybe never use fcitx before.
> > > Setting up on debian similar in other distro, open fcitx5 and add Unikey, but can use im-config to choose ibus or fcitx more easily
> 
> Can you write something there? I've never used Debian. TIA.

Can you test with ibus-bamboo? Fcitx5-Unikey 5.0.12 in Debian Testing don't have surrounding, they must build it manually from git.

2022-12-20 01:37 UTC, wengxt commented
> @zenfas Do you have experience in setting up fcitx-unikey in Debian? https://bugs.documentfoundation.org/show_bug.cgi?id=152519

I replied about the more detailed information on what need to be fixed. My suggestion for such bug reporting is that, don't use specific input method to be example, read the code and find the exact place they interact with input method.

There's just too much levels if you ask them to check how unikey interacts with libreoffice.

2022-12-21 01:01 UTC, wengxt requested changes
Is there anything else to add here? Overall it looks good to me, but I'd also like to see some test cases for this feature. You should be able to set fake surrounding text for input context.
InputContext* can be obtained by icManager().findByUUID

2022-12-21 01:25 UTC, trmdi commented
@wengxt btw, could you have a look at https://github.com/fcitx/fcitx5-unikey/pull/34#issuecomment-1353089573?
It seems Kate already sets the selection, but somehow fcitx doesn't get it.

2022-12-21 03:08 UTC, wengxt commented
> There is still an issue with Kate. When you have only one letter "a" in the document (a committed str), then press Ctrl+A, and type another "a", the existing "a" is not removed before the new "a" is inserted. It does not happen in other places, also not happen in Kate when you select the text with Shift+arrow key. Not sure how to solve this issue. Probably a Kate's bug? Do you have any suggestion @wengxt ? SurroundingText's selectedText is wrong in this case, I can't use it to check.

Can you check if your ktexteditor has this commit?
https://invent.kde.org/frameworks/ktexteditor/-/merge_requests/225 , based on the history it should be included in ktexteditor 5.89+

I'm not sure if I understand your issue, here's what I tried:
1. type a with en keyboard
2. switch to unikey
3. type a

I got an "a" in preedit and old selected "a" is removed.

2022-12-21 03:12 UTC, trmdi commented
Did you test with this PR?
1, type "a" in kate
2, switch to unikey
3, press ctrl+a (this step is inportant)
4, type "s"

Expect: "s"
Actual: "á"

2022-12-21 03:17 UTC, wengxt commented
> Did you test with this PR? 1, type "a" in kate 2, switch to unikey 3, press ctrl+a (this step is inportant) 4, type "s"
> 
> Expect: "s" Actual: "á"

ah, I see what you mean, yeah, previous post was not using this PR.

But I actually with this PR can get á without problem.

Can you check if you also updated fcitx5-qt to git version?

2022-12-21 03:22 UTC, trmdi commented
> But I actually with this PR can get á without problem.

My expectation is we should get "s" here.

2022-12-21 03:25 UTC, wengxt commented
Also as for ctrl + a thing, you need to pay attention where the cursor (black) blinks.

E.g. following are different
![图片](https://user-images.githubusercontent.com/259684/208812651-b4821e1a-fee3-4f6b-b86c-47b11f0ba331.png)

![图片](https://user-images.githubusercontent.com/259684/208812675-b4e1ed50-08a0-4c93-a70e-f5d5c422cc50.png)

But indeed, kate seems to be missing some surrounding notification when ctrl + a is pressed, or, it doesn't handle the ctrl + a cursor correctly. one side proof for this theory is that
Suppose you have abcd in the doc, then if you move cursor to the end of the doc, and press Ctrl + A, then you press "shift + left", the selected text will be "d", instead of "abc". 
If you manually shift + arrow to select all "abcd", although it looks the same as Ctrl + A, the shift + left will make it select "abc".

2022-12-21 03:28 UTC, wengxt commented
I think the bug is in kate's ctrl + A implementation, the kate internal state is not even consistent after ctrl + A.

2022-12-21 17:24 UTC, trmdi commented on unikey/ukengine.cpp
> +    static const std::map<int, UkKeyEvName> map_{
Basically those are copied from UkEngine::process()

2022-12-21 23:18 UTC, wengxt requested changes

2022-12-21 23:18 UTC, wengxt commented on src/unikey-im.cpp
> +    for (int i = 0; i < vnl_lastChar; i++) {
As I said, you're actually doing a reverse look up before, the static const trick in the old code is simply to ensure that the mapping is intialized only once. You should use unordered_map<uint32, VnLexiName> for this function.

See https://stackoverflow.com/questions/61109814/is-there-any-purpose-of-declaring-lambda-followed-by-immediately-invocation-to-i about how this trick works. (I just randomly google'd a relevant link)

2022-12-21 23:18 UTC, wengxt commented on src/unikey-im.cpp
> +        if (keyEvent.rawKey().sym() >= FcitxKey_exclam &&
Feels like Key::isSimple() can replace this? Also, key() seems to be easier to use in this case. Which is basically rawKey().normalize()

https://codedocs.xyz/fcitx/fcitx5/group__FcitxUtils.html#gaee771a4a09c07a97ed888ef2950858cc

2022-12-21 23:18 UTC, wengxt commented on src/unikey-im.cpp
> +    for (int i = 0; i < vnl_lastChar; i++) {
Also, while you want to have charToVnLexi, you can also keep isVniChar as `{ return charToVnLexi(c)  != vnl_nonVnChar; } ` for code readability.

2022-12-21 23:18 UTC, wengxt commented on src/unikey-im.cpp
> +        for (unsigned int i = 1; i <= length; ++i) {
This loop is not very efficient (O(n^2)).  utf8::nextNChar will need to scan through all the character from text.begin() to cursor - i.

So I think the code here is just trying to find the "longest" vni word before cursor.

So here's what I would do:
1. Since we already have a hard limit: MAX_LENGTH_VNWORD, that means at most we need to check the string from start = max(0, cursor - MAX_LENGTH_VNWORD - 1) to cursor. The start point is cursor - MAX_LENGTH_VNWORD - 1 because we want to check one more character to see if the word is longer than MAX_LENGTH_VNWORD.
2. We just keep calling utf8::getchar, or just use MakeUTF8CharRange. If we hit a non vn char during the scan, we reset the chars to empty and start appending again.

Also, you may reserve the chars string ahead of time.
That way, we would use at most O(MAX_LENGTH_VNWORD) time.

2022-12-22 01:55 UTC, wengxt commented
@trmdi I did bisect and believe kate issue an regression at https://invent.kde.org/frameworks/ktexteditor/-/commit/116dc5c4e43f2e2be08ad0bf3c10e8df2d0906bd , which intended to fix another issue.

2022-12-22 04:35 UTC, wengxt commented
Send a PR for your "Select all" issue: https://invent.kde.org/frameworks/ktexteditor/-/merge_requests/457

@trmdi this PR description says "Not yet completed but basically the core is done.", is it done by now except my change request or you still want to add something more?

2022-12-22 16:12 UTC, trmdi commented on src/unikey-im.cpp
> +        for (unsigned int i = 1; i <= length; ++i) {
Hopefully I do it as you expected. My coding skill is not really good.

2022-12-22 16:27 UTC, trmdi commented
> Send a PR for your "Select all" issue: https://invent.kde.org/frameworks/ktexteditor/-/merge_requests/457
> 
> @trmdi this PR description says "Not yet completed but basically the core is done.", is it done by now except my change request or you still want to add something more?

Basically it's done now. I will make new PRs when needed.

2022-12-23 01:52 UTC, zenfas commented
@trmdi I see parameter MAX_CONTEXT_SIZE, why don't reuse it and I see you make new one MAX_LENGTH_VNWORD

2022-12-23 02:00 UTC, zenfas commented
> > Send a PR for your "Select all" issue: https://invent.kde.org/frameworks/ktexteditor/-/merge_requests/457
> > @trmdi this PR description says "Not yet completed but basically the core is done.", is it done by now except my change request or you still want to add something more?
> 
> Basically it's done now. I will make new PRs when needed. Oops... Wait... I've just found a new bug...
> 
> Steps to reproduce:
> 
>     * In Firefox's Address bar, type "ab"
> 
>     * Select "b" (Shift+left or use your mouse)
> 
>     * type "c"
> 
> 
> Result: "acb" Expect: "ac"
> 
> Not happen in Kate, but interestingly it also happens with Android Laban Key. Will rethink about this tomorrow...

I can't preproduce you issue on Firefox Android with Laban Key

Uploading Screenrecorder-2022-12-23-08-57-41-703.mp4…

2022-12-23 02:04 UTC, trmdi commented
> I can't preproduce you issue on Firefox Android with Laban Key

Try in Zalo.

2022-12-23 02:22 UTC, zenfas commented
> > I can't preproduce you issue on Firefox Android with Laban Key
> 
> Try in Zalo, SS Internet... I don't use FF on Android so didn't test it.

Opps, sorry, my mistake. Issue also happen in Firefox with Laban key. Gboard works fine

2022-12-23 02:30 UTC, wengxt commented
> > Send a PR for your "Select all" issue: https://invent.kde.org/frameworks/ktexteditor/-/merge_requests/457
> > @trmdi this PR description says "Not yet completed but basically the core is done.", is it done by now except my change request or you still want to add something more?
> 
> Basically it's done now. I will make new PRs when needed. Oops... Wait... I've just found a new bug...
> 
> Steps to reproduce:
> 
>     * In Firefox's Address bar, type "ab"
> 
>     * Select "b" (Shift+left or use your mouse)
> 
>     * type "c"
> 
> 
> Result: "acb" Expect: "ac"
> 
> Not happen in Kate, but interestingly it also happens with Android Laban Key. Will rethink about this tomorrow...



> 

Gtk3 doesn't have a way to report anchor position.
In Gtk3 we only use some hack (probing the widget type) to do it.
https://github.com/fcitx/fcitx5-gtk/blob/master/gtk3/fcitximcontext.cpp#L1079

set_surrounding_with_selection is only available in Gtk 4.2+.

One possible workaround from my pov is that, maybe before you call deleteSurrounding, maybe you can try to initiate a commitString("") to see if it can help clear the selection?

If I can't work, my suggestion is that, don't bother fix it.

2022-12-23 02:31 UTC, wengxt commented
Android thing is totally irrelevant here. No need to think about it.

2022-12-23 03:35 UTC, zenfas commented
One more thing @trmdi , if use Composite Unicode, maximum should be 8 not 7

2022-12-23 03:47 UTC, zenfas commented
And another charset: TCVN3 7, VNI Win 8, VIQR 9; I don't know how to type for BK HCM2, CString, NCR Decimal, NCR Hex => at least, maximum should be 9 for VIQR charset code.

2022-12-23 03:53 UTC, trmdi commented
@zenfas This feature only supports Precomposed Unicode. How do you use Decomposed Unicode?
That MAX is the maximum length of VN words. The longest one is "nghiêng".

2022-12-23 04:03 UTC, zenfas commented
> @zenfas This feature only supports Precomposed Unicode. How do you use Decomposed Unicode? Nowadays the standard charset for VN should be Precomposed Unicode.
> 
> That MAX is the maximum length of VN words. The longest one is "nghiêng".

How about case user use another charset (bảng mã), small people still use it (specially in government, some people still use TCVN and VNI Windows)
Nghiêng in VNI Window is 8
Nghiêng in VIQR is 9

Do we have any problem with higher value @trmdi ?

2022-12-23 04:10 UTC, zenfas commented
When you replace MAX_CONTEXT_SIZE by MAX_LENGTH_VNWORD must be make sure that all charsets support by fcitx5-unikey should work well like before.

2022-12-23 04:11 UTC, trmdi commented
> > @zenfas This feature only supports Precomposed Unicode. How do you use Decomposed Unicode? Nowadays the standard charset for VN should be Precomposed Unicode.
> > That MAX is the maximum length of VN words. The longest one is "nghiêng".
> 
> How about case user use another charset (bảng mã), small people still use it (specially in government, some people still use TCVN and VNI Windows) Nghiêng in VNI Window is 8 Nghiêng in VIQR is 9
> 
> Do we have any problem with higher value @trmdi ?

Those ones are old and not recommended nowadays, I don't want to support them.
You could make a new PR for your need.

2022-12-23 04:12 UTC, trmdi commented
> When you replace MAX_CONTEXT_SIZE by MAX_LENGTH_VNWORD must be make sure that all charsets support by fcitx5-unikey should work well like before.

This is not related not anything else.

2022-12-23 04:18 UTC, zenfas commented
If your PR break some charsets function, you should remove all these charsets from code support of fcitx5-unikey completely. If fcitx5-unikey still support these charsets, they must work well. I don't agree if PR break them. If you work with gov organizations, you will see a lot of their documents and software still use old charset (special TVCN and VNI Windows), Unikey support well now, should keep it

2022-12-23 04:22 UTC, trmdi commented
> If your PR break some charsets function, you should remove all these charsets from code support of fcitx5-unikey completely. If fcitx5-unikey still support these charsets, they must work well. I don't agree if PR break them. If you work with gov organizations, you will see a lot of their documents and software still use old charset (special TVCN and VNI Windows), Unikey support well now, should keep it

Nothing is broken by this PR!

2022-12-23 09:55 UTC, trmdi commented on src/unikey-im.cpp
> +        for (unsigned int i = 1; i <= length; ++i) {
Revert to the older code with a minor adjustment, it performs a bit better.

2022-12-26 15:46 UTC, trmdi commented
> Send a PR for your "Select all" issue: https://invent.kde.org/frameworks/ktexteditor/-/merge_requests/457

@wengxt When trying this patch, I've found that this solved my "Select all" issue, but just for the case the doc has one line. It still fails when we have more than one lines. Not sure if there is still something that could be improved?

2022-12-26 15:56 UTC, wengxt commented
@trmdi that is hardcoded in the ktexteditor code. The anchor will not return a meaningful value if it is multi line selection. I don't know the reason for it, but i guess it can be somehow improved.

2022-12-31 03:19 UTC, trmdi commented
@wengxt Can this be megered now?

2023-01-04 01:33 UTC, wengxt commented
I updated the some code my self to resolve the comment and added some more test cases.

2023-01-04 01:33 UTC, merged